"""
scenarios/scenario_duplicate_inventory.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this scenario, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

import tkinter as tk
from tkinter import messagebox

from common import (
    PALETTE, FONT_SMALL, FONT_TITLE, FONT_HEAD,
    styled_label, styled_entry, styled_button, separator,
    LogPanel, ResultCard,
)
from db import Database

import queries.query_duplicate_inventory_detect as q_detect
import queries.query_duplicate_inventory_fix_cases as q_fix_cases
import queries.query_duplicate_inventory_fix_allocations as q_fix_allocations
import queries.query_duplicate_inventory_fix_qa_statuses as q_fix_qa_statuses

QUERIES = [q_detect, q_fix_cases, q_fix_allocations, q_fix_qa_statuses]


class ScenarioDuplicateInventory(tk.Frame):

    TITLE          = "Duplicate Inventory"
    ICON           = "⧉"
    ENVIRONMENTS   = ['PROD', 'QA']
    BUSINESS_UNITS = ['Beef/Pork']

    def __init__(self, parent, log: LogPanel, db: Database, **kw):
        kw.setdefault("bg", PALETTE["surface"])
        super().__init__(parent, **kw)
        self._log        = log
        self._db         = db
        self._param_vars = {}  # param_name → tk.StringVar
        self._cards      = {}  # query module → ResultCard
        self._build()

    def _build(self):
        hdr = tk.Frame(self, bg=PALETTE["surface2"], pady=10, padx=14)
        hdr.pack(fill="x")
        styled_label(hdr, f"{self.ICON}  {self.TITLE}",
                     font=FONT_TITLE, color=PALETTE["accent_text"]).pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        inp = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        inp.pack(fill="x")
        pass  # no user parameters required

        btn_row = tk.Frame(inp, bg=PALETTE["surface"])
        btn_row.pack(fill="x", pady=(4, 0))
        self._run_btn = styled_button(btn_row, "▶  Run All Checks", self._run, width=18)
        self._run_btn.pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        self._overall_lbl = tk.Label(
            self, text="Click Run All Checks to begin.",
            bg=PALETTE["surface"], fg=PALETTE["text_dim"],
            font=FONT_SMALL, justify="left", anchor="w",
        )
        self._overall_lbl.pack(anchor="w", padx=14, pady=(0, 10))

        cards_frame = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        cards_frame.pack(fill="both", expand=True)
        card_detect = ResultCard(cards_frame, title=q_detect.TITLE, description=q_detect.DESCRIPTION)
        card_detect.pack(fill="x", pady=(0, 8))
        self._cards[q_detect] = card_detect
        card_fix_cases = ResultCard(cards_frame, title=q_fix_cases.TITLE, description=q_fix_cases.DESCRIPTION)
        card_fix_cases.pack(fill="x", pady=(0, 8))
        self._cards[q_fix_cases] = card_fix_cases
        card_fix_allocations = ResultCard(cards_frame, title=q_fix_allocations.TITLE, description=q_fix_allocations.DESCRIPTION)
        card_fix_allocations.pack(fill="x", pady=(0, 8))
        self._cards[q_fix_allocations] = card_fix_allocations
        card_fix_qa_statuses = ResultCard(cards_frame, title=q_fix_qa_statuses.TITLE, description=q_fix_qa_statuses.DESCRIPTION)
        card_fix_qa_statuses.pack(fill="x", pady=(0, 8))
        self._cards[q_fix_qa_statuses] = card_fix_qa_statuses

    def _run(self):
        if not self._db.connected:
            messagebox.showerror("Not Connected", "Please connect to a plant first.")
            return

        self._run_btn.config(state="disabled", text="Running...")
        self._overall_lbl.config(text="Running checks...", fg=PALETTE["text_dim"])
        self._cards[q_detect].set_running()
        self._cards[q_fix_cases].set_running()
        self._cards[q_fix_allocations].set_running()
        self._cards[q_fix_qa_statuses].set_running()

        self._log.banner("Duplicate Inventory")

        import threading as _threading
        total_queries = 4
        completed     = [0]
        results_store = {}
        lock          = _threading.Lock()

        def _finish_one(qry, result):
            with lock:
                results_store[qry] = result
                completed[0] += 1
                done = completed[0]
            self.after(0, lambda q=qry, r=result: self._apply_result(q, r))
            if done == total_queries:
                self.after(0, lambda: self._finish(results_store))

        def _make_skipped(reason="Skipped"):
            from common import QueryResult
            r = QueryResult()
            r.status  = "_skipped"
            r.headline = reason
            return r

        def _thread_0():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["detect"] = q_detect.run()
            _finish_one(q_detect, _rs["detect"])
            if getattr(_rs["detect"], "dataframe", None):
                _dfs.update(_rs["detect"].dataframe)
            # ── Level 1 (3 queries in parallel) ─────────────────
            _ev_1  = _t.Event()
            _cnt_1 = [3]
            _lck_1 = _t.Lock()
            def _l1_fix_cases(_q_id="fix_cases"):
                _rs["fix_cases"] = q_fix_cases.run(df=_dfs if _dfs else None)
                _finish_one(q_fix_cases, _rs["fix_cases"])
                with _lck_1:
                    _cnt_1[0] -= 1
                    if _cnt_1[0] == 0:
                        _ev_1.set()
            def _l1_fix_allocations(_q_id="fix_allocations"):
                _rs["fix_allocations"] = q_fix_allocations.run(df=_dfs if _dfs else None)
                _finish_one(q_fix_allocations, _rs["fix_allocations"])
                with _lck_1:
                    _cnt_1[0] -= 1
                    if _cnt_1[0] == 0:
                        _ev_1.set()
            def _l1_fix_qa_statuses(_q_id="fix_qa_statuses"):
                _rs["fix_qa_statuses"] = q_fix_qa_statuses.run(df=_dfs if _dfs else None)
                _finish_one(q_fix_qa_statuses, _rs["fix_qa_statuses"])
                with _lck_1:
                    _cnt_1[0] -= 1
                    if _cnt_1[0] == 0:
                        _ev_1.set()
            _t.Thread(target=_l1_fix_cases, daemon=True).start()
            _t.Thread(target=_l1_fix_allocations, daemon=True).start()
            _t.Thread(target=_l1_fix_qa_statuses, daemon=True).start()
            _ev_1.wait()
            _r_tmp = _rs.get("fix_cases")
            if _r_tmp and getattr(_r_tmp, "dataframe", None):
                _dfs.update(_r_tmp.dataframe)
            _r_tmp = _rs.get("fix_allocations")
            if _r_tmp and getattr(_r_tmp, "dataframe", None):
                _dfs.update(_r_tmp.dataframe)
            _r_tmp = _rs.get("fix_qa_statuses")
            if _r_tmp and getattr(_r_tmp, "dataframe", None):
                _dfs.update(_r_tmp.dataframe)


        import threading as _t
        _t.Thread(target=_thread_0, daemon=True).start()

    def _apply_result(self, qry, result):
        card = self._cards.get(qry)
        if card is None:
            return
        self._log.flush_query_result(result)
        if result.status == "_skipped":
            card.set_skipped(result.headline)
        else:
            card.set_result(result)

    def _finish(self, results_store: dict):
        self._run_btn.config(state="normal", text="▶  Run All Checks")
        errors = issues = skipped = 0
        for r in results_store.values():
            if r.status == "_skipped":   skipped += 1
            elif r.status == "error":    errors  += 1
            elif r.status == "issues_found": issues += 1
        ran   = len(results_store) - skipped
        clean = ran - issues - errors
        if errors:
            self._overall_lbl.config(
                text=f"✘  {errors} query error(s). Check the activity log.",
                fg=PALETTE["error"])
        elif issues:
            self._overall_lbl.config(
                text=f"✘  {issues} of {ran} check(s) found issues.  {clean} passed.",
                fg=PALETTE["warning"])
        else:
            self._overall_lbl.config(
                text=f"✔  All {ran} check(s) passed.",
                fg=PALETTE["success"])
