"""
scenarios/scenario_automove_check.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this scenario, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

import tkinter as tk
from tkinter import messagebox

from common import (
    PALETTE, FONT_SMALL, FONT_TITLE, FONT_HEAD,
    styled_label, styled_entry, styled_button, separator,
    LogPanel, ResultCard,
)
from db import Database

import queries.query_automove_check_query_1 as q_query_1
import queries.query_automove_check_query_2 as q_query_2

QUERIES = [q_query_1, q_query_2]


class ScenarioAutomoveCheck(tk.Frame):

    TITLE          = "Automove check"
    ICON           = ""
    ENVIRONMENTS   = ['PROD', 'QA']
    BUSINESS_UNITS = ['Beef/Pork']

    def __init__(self, parent, log: LogPanel, db: Database, **kw):
        kw.setdefault("bg", PALETTE["surface"])
        super().__init__(parent, **kw)
        self._log        = log
        self._db         = db
        self._param_vars = {}  # param_name → tk.StringVar
        self._cards      = {}  # query module → ResultCard
        self._build()

    def _build(self):
        hdr = tk.Frame(self, bg=PALETTE["surface2"], pady=10, padx=14)
        hdr.pack(fill="x")
        styled_label(hdr, f"{self.ICON}  {self.TITLE}",
                     font=FONT_TITLE, color=PALETTE["accent_text"]).pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        inp = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        inp.pack(fill="x")
        styled_label(inp, "DeliveryNumber", color=PALETTE["text"], font=FONT_HEAD).pack(anchor="w", pady=(0, 4))
        row_DeliveryNumber = tk.Frame(inp, bg=PALETTE["surface"])
        row_DeliveryNumber.pack(fill="x", pady=(0, 8))
        self._param_vars["DeliveryNumber"] = tk.StringVar()
        e_DeliveryNumber = styled_entry(row_DeliveryNumber, width=28)
        e_DeliveryNumber.config(textvariable=self._param_vars["DeliveryNumber"])
        e_DeliveryNumber.pack(side="left", padx=(0, 10), ipady=5)
        e_DeliveryNumber.bind("<Return>", lambda e: self._run())

        btn_row = tk.Frame(inp, bg=PALETTE["surface"])
        btn_row.pack(fill="x", pady=(4, 0))
        self._run_btn = styled_button(btn_row, "▶  Run All Checks", self._run, width=18)
        self._run_btn.pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        self._overall_lbl = tk.Label(
            self, text="Click Run All Checks to begin.",
            bg=PALETTE["surface"], fg=PALETTE["text_dim"],
            font=FONT_SMALL, justify="left", anchor="w",
        )
        self._overall_lbl.pack(anchor="w", padx=14, pady=(0, 10))

        cards_frame = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        cards_frame.pack(fill="both", expand=True)
        card_query_1 = ResultCard(cards_frame, title=q_query_1.TITLE, description=q_query_1.DESCRIPTION)
        card_query_1.pack(fill="x", pady=(0, 8))
        self._cards[q_query_1] = card_query_1
        card_query_2 = ResultCard(cards_frame, title=q_query_2.TITLE, description=q_query_2.DESCRIPTION)
        card_query_2.pack(fill="x", pady=(0, 8))
        self._cards[q_query_2] = card_query_2

    def _run(self):
        if not self._db.connected:
            messagebox.showerror("Not Connected", "Please connect to a plant first.")
            return

        self._run_btn.config(state="disabled", text="Running...")
        self._overall_lbl.config(text="Running checks...", fg=PALETTE["text_dim"])
        self._cards[q_query_1].set_running()
        self._cards[q_query_2].set_running()

        self._log.banner("Automove check")

        import threading as _threading
        total_queries = 2
        completed     = [0]
        results_store = {}
        lock          = _threading.Lock()

        def _finish_one(qry, result):
            with lock:
                results_store[qry] = result
                completed[0] += 1
                done = completed[0]
            self.after(0, lambda q=qry, r=result: self._apply_result(q, r))
            if done == total_queries:
                self.after(0, lambda: self._finish(results_store))

        def _make_skipped(reason="Skipped"):
            from common import QueryResult
            r = QueryResult()
            r.status  = "_skipped"
            r.headline = reason
            return r

        def _thread_0():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["query_1"] = q_query_1.run(self._param_vars.get("DeliveryNumber", tk.StringVar()).get().strip())
            _finish_one(q_query_1, _rs["query_1"])
            if getattr(_rs["query_1"], "dataframe", None):
                _dfs.update(_rs["query_1"].dataframe)

        def _thread_1():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["query_2"] = q_query_2.run()
            _finish_one(q_query_2, _rs["query_2"])
            if getattr(_rs["query_2"], "dataframe", None):
                _dfs.update(_rs["query_2"].dataframe)


        import threading as _t
        _t.Thread(target=_thread_0, daemon=True).start()
        _t.Thread(target=_thread_1, daemon=True).start()

    def _apply_result(self, qry, result):
        card = self._cards.get(qry)
        if card is None:
            return
        self._log.flush_query_result(result)
        if result.status == "_skipped":
            card.set_skipped(result.headline)
        else:
            card.set_result(result)

    def _finish(self, results_store: dict):
        self._run_btn.config(state="normal", text="▶  Run All Checks")
        errors = issues = skipped = 0
        for r in results_store.values():
            if r.status == "_skipped":   skipped += 1
            elif r.status == "error":    errors  += 1
            elif r.status == "issues_found": issues += 1
        ran   = len(results_store) - skipped
        clean = ran - issues - errors
        if errors:
            self._overall_lbl.config(
                text=f"✘  {errors} query error(s). Check the activity log.",
                fg=PALETTE["error"])
        elif issues:
            self._overall_lbl.config(
                text=f"✘  {issues} of {ran} check(s) found issues.  {clean} passed.",
                fg=PALETTE["warning"])
        else:
            self._overall_lbl.config(
                text=f"✔  All {ran} check(s) passed.",
                fg=PALETTE["success"])
