"""
scenarios/scenario_carcass.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this scenario, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

import tkinter as tk
from tkinter import messagebox

from common import (
    PALETTE, FONT_SMALL, FONT_TITLE, FONT_HEAD,
    styled_label, styled_entry, styled_button, separator,
    LogPanel, ResultCard,
)
from db import Database

import queries.query_carcass_backtag as q_backtag
import queries.query_carcass_hot as q_hot
import queries.query_carcass_epv as q_epv
import queries.query_carcass_rawinterface as q_rawinterface
import queries.query_carcass_killgroup as q_killgroup
import queries.query_carcass_lotdetails as q_lotdetails

QUERIES = [q_backtag, q_hot, q_epv, q_rawinterface, q_killgroup, q_lotdetails]


class ScenarioCarcassLookup(tk.Frame):

    TITLE          = "Carcass Lookup"
    ICON           = "🐖"
    ENVIRONMENTS   = ['PROD', 'QA']
    BUSINESS_UNITS = ['Beef/Pork']

    def __init__(self, parent, log: LogPanel, db: Database, **kw):
        kw.setdefault("bg", PALETTE["surface"])
        super().__init__(parent, **kw)
        self._log        = log
        self._db         = db
        self._param_vars = {}  # param_name → tk.StringVar
        self._cards      = {}  # query module → ResultCard
        self._build()

    def _build(self):
        hdr = tk.Frame(self, bg=PALETTE["surface2"], pady=10, padx=14)
        hdr.pack(fill="x")
        styled_label(hdr, f"{self.ICON}  {self.TITLE}",
                     font=FONT_TITLE, color=PALETTE["accent_text"]).pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        inp = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        inp.pack(fill="x")
        styled_label(inp, "Carcass ID", color=PALETTE["text"], font=FONT_HEAD).pack(anchor="w", pady=(0, 4))
        row_carcass_id = tk.Frame(inp, bg=PALETTE["surface"])
        row_carcass_id.pack(fill="x", pady=(0, 8))
        self._param_vars["carcass_id"] = tk.StringVar()
        e_carcass_id = styled_entry(row_carcass_id, width=28)
        e_carcass_id.config(textvariable=self._param_vars["carcass_id"])
        e_carcass_id.pack(side="left", padx=(0, 10), ipady=5)
        e_carcass_id.bind("<Return>", lambda e: self._run())

        btn_row = tk.Frame(inp, bg=PALETTE["surface"])
        btn_row.pack(fill="x", pady=(4, 0))
        self._run_btn = styled_button(btn_row, "▶  Run All Checks", self._run, width=18)
        self._run_btn.pack(side="left")

        separator(self).pack(fill="x", padx=10, pady=10)

        self._overall_lbl = tk.Label(
            self, text="Click Run All Checks to begin.",
            bg=PALETTE["surface"], fg=PALETTE["text_dim"],
            font=FONT_SMALL, justify="left", anchor="w",
        )
        self._overall_lbl.pack(anchor="w", padx=14, pady=(0, 10))

        cards_frame = tk.Frame(self, bg=PALETTE["surface"], padx=14)
        cards_frame.pack(fill="both", expand=True)
        card_backtag = ResultCard(cards_frame, title=q_backtag.TITLE, description=q_backtag.DESCRIPTION)
        card_backtag.pack(fill="x", pady=(0, 8))
        self._cards[q_backtag] = card_backtag
        card_hot = ResultCard(cards_frame, title=q_hot.TITLE, description=q_hot.DESCRIPTION)
        card_hot.pack(fill="x", pady=(0, 8))
        self._cards[q_hot] = card_hot
        card_epv = ResultCard(cards_frame, title=q_epv.TITLE, description=q_epv.DESCRIPTION)
        card_epv.pack(fill="x", pady=(0, 8))
        self._cards[q_epv] = card_epv
        card_rawinterface = ResultCard(cards_frame, title=q_rawinterface.TITLE, description=q_rawinterface.DESCRIPTION)
        card_rawinterface.pack(fill="x", pady=(0, 8))
        self._cards[q_rawinterface] = card_rawinterface
        card_killgroup = ResultCard(cards_frame, title=q_killgroup.TITLE, description=q_killgroup.DESCRIPTION)
        card_killgroup.pack(fill="x", pady=(0, 8))
        self._cards[q_killgroup] = card_killgroup
        card_lotdetails = ResultCard(cards_frame, title=q_lotdetails.TITLE, description=q_lotdetails.DESCRIPTION)
        card_lotdetails.pack(fill="x", pady=(0, 8))
        self._cards[q_lotdetails] = card_lotdetails

    def _run(self):
        if not self._db.connected:
            messagebox.showerror("Not Connected", "Please connect to a plant first.")
            return

        self._run_btn.config(state="disabled", text="Running...")
        self._overall_lbl.config(text="Running checks...", fg=PALETTE["text_dim"])
        self._cards[q_backtag].set_running()
        self._cards[q_hot].set_running()
        self._cards[q_epv].set_running()
        self._cards[q_rawinterface].set_running()
        self._cards[q_killgroup].set_running()
        self._cards[q_lotdetails].set_running()

        self._log.banner("Carcass Lookup")

        import threading as _threading
        total_queries = 6
        completed     = [0]
        results_store = {}
        lock          = _threading.Lock()

        def _finish_one(qry, result):
            with lock:
                results_store[qry] = result
                completed[0] += 1
                done = completed[0]
            self.after(0, lambda q=qry, r=result: self._apply_result(q, r))
            if done == total_queries:
                self.after(0, lambda: self._finish(results_store))

        def _make_skipped(reason="Skipped"):
            from common import QueryResult
            r = QueryResult()
            r.status  = "_skipped"
            r.headline = reason
            return r

        def _thread_0():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["backtag"] = q_backtag.run(self._param_vars.get("carcass_id", tk.StringVar()).get().strip())
            _finish_one(q_backtag, _rs["backtag"])
            if getattr(_rs["backtag"], "dataframe", None):
                _dfs.update(_rs["backtag"].dataframe)
            # ── Gate: backtag must succeed for remaining queries ──
            if "backtag" in _rs and _rs["backtag"].status in ("error", "_skipped"):
                _rs["killgroup"] = _make_skipped("Skipped — backtag gate failed")
                _finish_one(q_killgroup, _rs["killgroup"])
                _rs["lotdetails"] = _make_skipped("Skipped — backtag gate failed")
                _finish_one(q_lotdetails, _rs["lotdetails"])
                return
            _raw_killgroup_killgroupid = (_rs.get("backtag") or _make_skipped()).extracted.get("killgroupid", "")
            if isinstance(_raw_killgroup_killgroupid, list):
                _killgroup_killgroupid_val = ", ".join(
                    "'" + str(v).replace("'", "''") + "'"
                    for v in _raw_killgroup_killgroupid
                )
            else:
                _s_killgroupid = str(_raw_killgroup_killgroupid)
                _killgroup_killgroupid_val = "'" + _s_killgroupid.replace("'", "''") + "'"
            _rs["killgroup"] = q_killgroup.run(_killgroup_killgroupid_val)
            _finish_one(q_killgroup, _rs["killgroup"])
            if getattr(_rs["killgroup"], "dataframe", None):
                _dfs.update(_rs["killgroup"].dataframe)
            # ── Gate: killgroup must succeed for remaining queries ──
            if "killgroup" in _rs and _rs["killgroup"].status in ("error", "_skipped"):
                _rs["lotdetails"] = _make_skipped("Skipped — killgroup gate failed")
                _finish_one(q_lotdetails, _rs["lotdetails"])
                return
            _raw_lotdetails_schedulegroup = (_rs.get("killgroup") or _make_skipped()).extracted.get("ScheduleGroup", "")
            if isinstance(_raw_lotdetails_schedulegroup, list):
                _lotdetails_schedulegroup_val = ", ".join(
                    "'" + str(v).replace("'", "''") + "'"
                    for v in _raw_lotdetails_schedulegroup
                )
            else:
                _s_schedulegroup = str(_raw_lotdetails_schedulegroup)
                _lotdetails_schedulegroup_val = "'" + _s_schedulegroup.replace("'", "''") + "'"
            _rs["lotdetails"] = q_lotdetails.run(_lotdetails_schedulegroup_val)
            _finish_one(q_lotdetails, _rs["lotdetails"])
            if getattr(_rs["lotdetails"], "dataframe", None):
                _dfs.update(_rs["lotdetails"].dataframe)

        def _thread_1():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["hot"] = q_hot.run(self._param_vars.get("carcass_id", tk.StringVar()).get().strip())
            _finish_one(q_hot, _rs["hot"])
            if getattr(_rs["hot"], "dataframe", None):
                _dfs.update(_rs["hot"].dataframe)

        def _thread_2():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["epv"] = q_epv.run(self._param_vars.get("carcass_id", tk.StringVar()).get().strip())
            _finish_one(q_epv, _rs["epv"])
            if getattr(_rs["epv"], "dataframe", None):
                _dfs.update(_rs["epv"].dataframe)

        def _thread_3():
            import threading as _t
            _rs  = {}   # query_id → QueryResult
            _dfs = {}   # TBL_KEY  → pd.DataFrame (from temp table parents)
            _rs["rawinterface"] = q_rawinterface.run(self._param_vars.get("carcass_id", tk.StringVar()).get().strip())
            _finish_one(q_rawinterface, _rs["rawinterface"])
            if getattr(_rs["rawinterface"], "dataframe", None):
                _dfs.update(_rs["rawinterface"].dataframe)


        import threading as _t
        _t.Thread(target=_thread_0, daemon=True).start()
        _t.Thread(target=_thread_1, daemon=True).start()
        _t.Thread(target=_thread_2, daemon=True).start()
        _t.Thread(target=_thread_3, daemon=True).start()

    def _apply_result(self, qry, result):
        card = self._cards.get(qry)
        if card is None:
            return
        self._log.flush_query_result(result)
        if result.status == "_skipped":
            card.set_skipped(result.headline)
        else:
            card.set_result(result)

    def _finish(self, results_store: dict):
        self._run_btn.config(state="normal", text="▶  Run All Checks")
        errors = issues = skipped = 0
        for r in results_store.values():
            if r.status == "_skipped":   skipped += 1
            elif r.status == "error":    errors  += 1
            elif r.status == "issues_found": issues += 1
        ran   = len(results_store) - skipped
        clean = ran - issues - errors
        if errors:
            self._overall_lbl.config(
                text=f"✘  {errors} query error(s). Check the activity log.",
                fg=PALETTE["error"])
        elif issues:
            self._overall_lbl.config(
                text=f"✘  {issues} of {ran} check(s) found issues.  {clean} passed.",
                fg=PALETTE["warning"])
        else:
            self._overall_lbl.config(
                text=f"✔  All {ran} check(s) passed.",
                fg=PALETTE["success"])
