"""
queries/query_pronto_warehouses.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

import json
from common import QueryResult
from db import db

TITLE       = "Pronto Warehouse Codes"
DESCRIPTION = "Loads Pronto warehouse code mappings from WorkstationApplicationSettings."

# WorkstationApplicationSettings stores miscellaneous configuration as key/value pairs
# scoped to a PackageName. The ProntoWhseCodeSFShippingPointMapping value is a JSON
# array that maps each Pronto warehouse code to its corresponding ShopFloor shipping point.
# Warehouse Codes Lookup
SQL_BLOCK_1 = """
    SELECT TOP 1 Value
    FROM WorkstationApplicationSettings WITH (READUNCOMMITTED)
    WHERE PackageName = 'Protein.ShopFloor.InterfaceTasks.ProntoFileInterface'
      AND Code        = 'ProntoWhseCodeSFShippingPointMapping'
"""
_SQL_BLOCK_1_EXEC = SQL_BLOCK_1


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()

    try:
        cursor = db.conn.cursor()
        cursor.execute(SQL_BLOCK_1)
        row = cursor.fetchone()
    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not row or not row[0]:
        result.status   = "issues_found"
        result.headline = "No Pronto warehouse mapping found in WorkstationApplicationSettings."
        result.add_message("warning", f"  ✘ {result.headline}")
        return result

    try:
        # The Value column stores a JSON array — parse it into a Python list of dicts
        warehouses = json.loads(row[0])
    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Failed to parse Value JSON — {exc}"
        result.add_message("error", result.headline)
        return result

    result.status  = "ok"
    result.headline = f"{len(warehouses)} warehouse code(s) loaded."

    # Store the parsed list so the Pronto Order Builder scenario can populate its dropdown
    result.extracted["warehouses"] = warehouses
    return result
