"""
queries/query_pronto_vendor.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db

TITLE       = "Vendor Lookup"
DESCRIPTION = "Fetches vendor name and address from ThirdParties by ThirdPartyId."

# ThirdParties holds supplier/vendor master data including address information.
# ThirdPartyId is the identifier used in the Pronto interface H (header) line.
# All returned fields map directly to H line positions in the order payload.
# Vendor Lookup
SQL_BLOCK_1 = """
    SELECT
        VendorName,
        Street1,
        Street2,
        City,
        ZipCode,
        StateProvince
    FROM ThirdParties
    WHERE ThirdPartyId = @third_party_id
"""
_SQL_BLOCK_1_EXEC = """
    SELECT
        VendorName,
        Street1,
        Street2,
        City,
        ZipCode,
        StateProvince
    FROM ThirdParties
    WHERE ThirdPartyId = ?
"""


def run(third_party_id: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()

    try:
        cursor = db.conn.cursor()
        cursor.execute(_SQL_BLOCK_1_EXEC, third_party_id)
        row = cursor.fetchone()
        cols = [col[0] for col in cursor.description]
        result.cols = cols
    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not row:
        result.status   = "issues_found"
        result.headline = f"No vendor found for ThirdPartyId: {third_party_id}"
        result.add_message("warning", f"  ✘ {result.headline}")
        return result

    result.status   = "ok"
    result.headline = f"Vendor found: {row[cols.index('VendorName')]}"

    # Store each address field in result.extracted so the order builder form can
    # auto-fill the vendor section without the analyst re-typing the data
    for col, val in zip(cols, row):
        result.extracted[col] = str(val) if val is not None else ""

    return result
