"""
queries/query_automove_check_query_2.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Replen results"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    SELECT
        PalletNumber,
        WarehouseLocationId,

        ------------------------------------------------------------------
        -- Diagnostic outcome
        ------------------------------------------------------------------
        CASE
            WHEN
                Fail_MinProductionDate +
                Fail_MaxProductionDate +
                Fail_MinWeight +
                Fail_MaxWeight +
                Fail_MinSellByDate +
                Fail_Expired +
                Fail_CommittedToAnotherDelivery +
                Fail_TaskAlreadyExists = 0
            THEN 'QUALIFIES'
            ELSE 'DOES NOT QUALIFY'
        END AS QualificationStatus,

        ------------------------------------------------------------------
        -- WHY IT FAILED (comma-separated)
        ------------------------------------------------------------------
        LTRIM(STUFF(
            CONCAT(
                CASE WHEN Fail_MinProductionDate = 1          THEN ', Production date too early'       ELSE '' END,
                CASE WHEN Fail_MaxProductionDate = 1          THEN ', Production date too late'        ELSE '' END,
                CASE WHEN Fail_MinWeight = 1                  THEN ', Weight below minimum'            ELSE '' END,
                CASE WHEN Fail_MaxWeight = 1                  THEN ', Weight above maximum'            ELSE '' END,
                CASE WHEN Fail_MinSellByDate = 1              THEN ', Sell-by date too early'           ELSE '' END,
                CASE WHEN Fail_Expired = 1                    THEN ', Pallet expired'                  ELSE '' END,
                CASE WHEN Fail_CommittedToAnotherDelivery = 1 THEN ', Already committed to delivery'   ELSE '' END,
                CASE WHEN Fail_TaskAlreadyExists = 1          THEN ', Task already exists'              ELSE '' END
            ),
            1, 1, ''
        )) AS FailureReasons

    FROM ReplenPalletDiagnostics
    ORDER BY WarehouseLocationId, PalletNumber;
"""

_SQL_BLOCK_1_EXEC = """
    SELECT
        PalletNumber,
        WarehouseLocationId,

        ------------------------------------------------------------------
        -- Diagnostic outcome
        ------------------------------------------------------------------
        CASE
            WHEN
                Fail_MinProductionDate +
                Fail_MaxProductionDate +
                Fail_MinWeight +
                Fail_MaxWeight +
                Fail_MinSellByDate +
                Fail_Expired +
                Fail_CommittedToAnotherDelivery +
                Fail_TaskAlreadyExists = 0
            THEN 'QUALIFIES'
            ELSE 'DOES NOT QUALIFY'
        END AS QualificationStatus,

        ------------------------------------------------------------------
        -- WHY IT FAILED (comma-separated)
        ------------------------------------------------------------------
        LTRIM(STUFF(
            CONCAT(
                CASE WHEN Fail_MinProductionDate = 1          THEN ', Production date too early'       ELSE '' END,
                CASE WHEN Fail_MaxProductionDate = 1          THEN ', Production date too late'        ELSE '' END,
                CASE WHEN Fail_MinWeight = 1                  THEN ', Weight below minimum'            ELSE '' END,
                CASE WHEN Fail_MaxWeight = 1                  THEN ', Weight above maximum'            ELSE '' END,
                CASE WHEN Fail_MinSellByDate = 1              THEN ', Sell-by date too early'           ELSE '' END,
                CASE WHEN Fail_Expired = 1                    THEN ', Pallet expired'                  ELSE '' END,
                CASE WHEN Fail_CommittedToAnotherDelivery = 1 THEN ', Already committed to delivery'   ELSE '' END,
                CASE WHEN Fail_TaskAlreadyExists = 1          THEN ', Task already exists'              ELSE '' END
            ),
            1, 1, ''
        )) AS FailureReasons

    FROM ReplenPalletDiagnostics
    ORDER BY WarehouseLocationId, PalletNumber;
"""


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
