"""
queries/query_duplicate_inventory_query_5.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Duplicte Inventory Detection Results"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    -- Return only the STALE duplicate rows (not the current/max record).
        -- CurrentInventoryId is the record we keep; DuplicateInventoryId is the one to remove.
        SELECT
            m.ProductionDate,
            m.ProductId,
            m.PalletNumber,
            m.Barcode,
            m.Weight,
            m.cnt                  AS DuplicateCount,      -- total copies of this barcode
            m.maxloc               AS CurrentLocation,      -- where the "keeper" record sits
            m.maxinvid             AS CurrentInventoryId,   -- InventoryId of the keeper record
            m.WarehouseLocationId  AS DuplicateLocation,    -- where the stale copy sits
            m.InventoryId          AS DuplicateInventoryId, -- InventoryId of the stale copy to remove
            m.CreatedDate,
            m.CreatedBy,
            m.ModifiedDate,
            m.ModifiedBy
        FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
        ON wal.LocationId = m.WarehouseLocationId
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON  wa.WarehouseId = wal.WarehouseId
        AND wa.AreaId      = wal.AreaId
    WHERE
        -- Exclude the keeper
        m.maxinvid <> m.InventoryId
        AND m.WarehouseLocationId NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')

        AND
    	(
    		-- Normal noise control
    		wa.IsAvailable = 1

    		OR
    		(
    			-- Override: BOTH InventoryIds have QA history
    			EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q1
    				WHERE q1.InventoryId = m.InventoryId
    			)
    			AND EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q2
    				WHERE q2.InventoryId = m.maxinvid
    			)
    		)
    	)

        ORDER BY m.ProductionDate
"""

_SQL_BLOCK_1_EXEC = """
    -- Return only the STALE duplicate rows (not the current/max record).
        -- CurrentInventoryId is the record we keep; DuplicateInventoryId is the one to remove.
        SELECT
            m.ProductionDate,
            m.ProductId,
            m.PalletNumber,
            m.Barcode,
            m.Weight,
            m.cnt                  AS DuplicateCount,      -- total copies of this barcode
            m.maxloc               AS CurrentLocation,      -- where the "keeper" record sits
            m.maxinvid             AS CurrentInventoryId,   -- InventoryId of the keeper record
            m.WarehouseLocationId  AS DuplicateLocation,    -- where the stale copy sits
            m.InventoryId          AS DuplicateInventoryId, -- InventoryId of the stale copy to remove
            m.CreatedDate,
            m.CreatedBy,
            m.ModifiedDate,
            m.ModifiedBy
        FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
        ON wal.LocationId = m.WarehouseLocationId
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON  wa.WarehouseId = wal.WarehouseId
        AND wa.AreaId      = wal.AreaId
    WHERE
        -- Exclude the keeper
        m.maxinvid <> m.InventoryId
        AND m.WarehouseLocationId NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')

        AND
    	(
    		-- Normal noise control
    		wa.IsAvailable = 1

    		OR
    		(
    			-- Override: BOTH InventoryIds have QA history
    			EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q1
    				WHERE q1.InventoryId = m.InventoryId
    			)
    			AND EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q2
    				WHERE q2.InventoryId = m.maxinvid
    			)
    		)
    	)

        ORDER BY m.ProductionDate
"""


def run(df: dict | None = None) -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        # ── DataFrame → VALUES CTE injection ────────────────────────────────
        import re as _re
        from common import build_values_cte as _bvc
        _cte_parts = []
        for _df_key in ["MaxInvID"]:
            if df and _df_key in df:
                _cte_parts.append(_bvc(df[_df_key], _df_key).removeprefix("WITH "))
        _cte_prefix = ("WITH " + ",\n".join(_cte_parts) + "\n") if _cte_parts else ""
        _sql_block_1 = _cte_prefix + _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols
        # ── Store result as named DataFrame for child queries ──────────────
        try:
            import pandas as _pd
            result.dataframe = {"MaxInvIDResults": _pd.DataFrame(
                [list(r) for r in rows], columns=cols
            )}
        except Exception:
            pass

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
