"""
queries/query_duplicate_inventory_detect.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Duplicate Inventory Detection"
DESCRIPTION = (
    "Finds barcodes with more than one active InventoryCase record. Excludes SHIPPED, SHIPRTN, ADJUST, and LVADJ from results."
)

# Build Temp Table
SQL_BLOCK_1 = """
    SET NOCOUNT ON;
    WITH MaxInvID AS (
        select
        -- Resolve the current "live" location for the highest InventoryId on this barcode.
        -- A location is "live" only if its WarehouseArea has IsAvailable = 1.
        (select top 1 warehouselocationid
        from Inventorycases ic with (readuncommitted)
        join WarehouseAreaLocations wal on wal.LocationId = ic.WarehouseLocationId
        join WarehouseAreas wa on wa.WarehouseId = wal.WarehouseId
                            and wa.AreaId = wal.AreaId
                            and wa.IsAvailable = 1
        where inventoryid = maxinvid
        ) maxloc
        ,cnt
        ,maxinvid
        ,toploc
        ,botloc
        ,x.PlantCode
        ,InventoryId
        ,ProductId
        ,x.Barcode
        ,BatchNumber
        ,PalletNumber
        ,InventoryStatusId
        ,SapStorageLocation
        ,EstNumber
        ,VendorLot
        ,EntryInventoryMovementTypeId
        ,EntryOrderNumber
        ,EntryOrderLineNumber
        ,EntryDate
        ,EntryDeliveryNumber
        ,EntryDeliveryLineNumber
        ,EntryShift
        ,ExitInventoryMovementTypeId
        ,ExitOrderNumber
        ,ExitOrderLineNumber
        ,ExitDate
        ,ExitShift
        ,Weight
        ,ProductionDate
        ,EntryPostedToSap
        ,ExitPostedToSap
        ,PostedToSapDate
        ,x.CreatedBy
        ,x.CreatedDate
        ,x.ModifiedBy
        ,x.ModifiedDate
        ,ExitDeliveryNumber
        ,ExitDeliveryLineNumber
        ,WarehouseLocationId
        ,IsNonSerializedPallet
        ,Qty
        ,ReceiveUOM
        from (
            -- Window functions run across ALL locations so cross-location duplicates are caught.
            -- cnt:      how many InventoryCase rows exist for this barcode (any location)
            -- maxinvid: the highest InventoryId for this barcode — treated as the "current" record
            -- toploc / botloc: alphabetically last and first locations for this barcode (diagnostic info)
            select count(1) over (partition by barcode) cnt
                , max(inventoryid) over (partition by barcode) maxinvid
                , max(WarehouseLocationId) over (partition by barcode) toploc
                , min(WarehouseLocationId) over (partition by barcode) botloc
                , * from InventoryCases with (readuncommitted)
        ) x
        -- Join to WarehouseAreas so we can filter to active areas only
        join WarehouseAreaLocations wal with (readuncommitted) on wal.LocationId = WarehouseLocationId
        join WarehouseAreas wa with (readuncommitted) on wa.WarehouseId = wal.WarehouseId and wa.AreaId = wal.AreaId
        -- Only keep barcodes that have more than one InventoryCase row
        where cnt > 1
        -- Exclude resolved/terminal locations — fix scripts should only target active records
        and WarehouseLocationId not in ('SHIPPED','SHIPRTN','ADJUST','LVADJ','HAM1','HAM2','BELLY','MHARV','BLEND1','BLEND2','BLEND3','BLEND4','BLEND5','BLEND6','TB2')
    )

    -- Return only the STALE duplicate rows (not the current/max record).
        -- CurrentInventoryId is the record we keep; DuplicateInventoryId is the one to remove.
        SELECT
            m.ProductionDate,
            m.ProductId,
            m.PalletNumber,
            m.Barcode,
            m.Weight,
            m.cnt                  AS DuplicateCount,      -- total copies of this barcode
            m.maxloc               AS CurrentLocation,      -- where the "keeper" record sits
            m.maxinvid             AS CurrentInventoryId,   -- InventoryId of the keeper record
            m.WarehouseLocationId  AS DuplicateLocation,    -- where the stale copy sits
            m.InventoryId          AS DuplicateInventoryId, -- InventoryId of the stale copy to remove
            m.CreatedDate,
            m.CreatedBy,
            m.ModifiedDate,
            m.ModifiedBy
        FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
        ON wal.LocationId = m.WarehouseLocationId
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON  wa.WarehouseId = wal.WarehouseId
        AND wa.AreaId      = wal.AreaId
    WHERE
        -- Exclude the keeper
        m.maxinvid <> m.InventoryId
        AND m.WarehouseLocationId NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')

        AND
    	(
    		-- Normal noise control
    		wa.IsAvailable = 1

    		OR
    		(
    			-- Override: BOTH InventoryIds have QA history
    			EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q1
    				WHERE q1.InventoryId = m.InventoryId
    			)
    			AND EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q2
    				WHERE q2.InventoryId = m.maxinvid
    			)
    		)
    	)

        ORDER BY m.ProductionDate
"""

_SQL_BLOCK_1_EXEC = """
    SET NOCOUNT ON;
    WITH MaxInvID AS (
        select
        -- Resolve the current "live" location for the highest InventoryId on this barcode.
        -- A location is "live" only if its WarehouseArea has IsAvailable = 1.
        (select top 1 warehouselocationid
        from Inventorycases ic with (readuncommitted)
        join WarehouseAreaLocations wal on wal.LocationId = ic.WarehouseLocationId
        join WarehouseAreas wa on wa.WarehouseId = wal.WarehouseId
                            and wa.AreaId = wal.AreaId
                            and wa.IsAvailable = 1
        where inventoryid = maxinvid
        ) maxloc
        ,cnt
        ,maxinvid
        ,toploc
        ,botloc
        ,x.PlantCode
        ,InventoryId
        ,ProductId
        ,x.Barcode
        ,BatchNumber
        ,PalletNumber
        ,InventoryStatusId
        ,SapStorageLocation
        ,EstNumber
        ,VendorLot
        ,EntryInventoryMovementTypeId
        ,EntryOrderNumber
        ,EntryOrderLineNumber
        ,EntryDate
        ,EntryDeliveryNumber
        ,EntryDeliveryLineNumber
        ,EntryShift
        ,ExitInventoryMovementTypeId
        ,ExitOrderNumber
        ,ExitOrderLineNumber
        ,ExitDate
        ,ExitShift
        ,Weight
        ,ProductionDate
        ,EntryPostedToSap
        ,ExitPostedToSap
        ,PostedToSapDate
        ,x.CreatedBy
        ,x.CreatedDate
        ,x.ModifiedBy
        ,x.ModifiedDate
        ,ExitDeliveryNumber
        ,ExitDeliveryLineNumber
        ,WarehouseLocationId
        ,IsNonSerializedPallet
        ,Qty
        ,ReceiveUOM
        from (
            -- Window functions run across ALL locations so cross-location duplicates are caught.
            -- cnt:      how many InventoryCase rows exist for this barcode (any location)
            -- maxinvid: the highest InventoryId for this barcode — treated as the "current" record
            -- toploc / botloc: alphabetically last and first locations for this barcode (diagnostic info)
            select count(1) over (partition by barcode) cnt
                , max(inventoryid) over (partition by barcode) maxinvid
                , max(WarehouseLocationId) over (partition by barcode) toploc
                , min(WarehouseLocationId) over (partition by barcode) botloc
                , * from InventoryCases with (readuncommitted)
        ) x
        -- Join to WarehouseAreas so we can filter to active areas only
        join WarehouseAreaLocations wal with (readuncommitted) on wal.LocationId = WarehouseLocationId
        join WarehouseAreas wa with (readuncommitted) on wa.WarehouseId = wal.WarehouseId and wa.AreaId = wal.AreaId
        -- Only keep barcodes that have more than one InventoryCase row
        where cnt > 1
        -- Exclude resolved/terminal locations — fix scripts should only target active records
        and WarehouseLocationId not in ('SHIPPED','SHIPRTN','ADJUST','LVADJ','HAM1','HAM2','BELLY','MHARV','BLEND1','BLEND2','BLEND3','BLEND4','BLEND5','BLEND6','TB2')
    )

    -- Return only the STALE duplicate rows (not the current/max record).
        -- CurrentInventoryId is the record we keep; DuplicateInventoryId is the one to remove.
        SELECT
            m.ProductionDate,
            m.ProductId,
            m.PalletNumber,
            m.Barcode,
            m.Weight,
            m.cnt                  AS DuplicateCount,      -- total copies of this barcode
            m.maxloc               AS CurrentLocation,      -- where the "keeper" record sits
            m.maxinvid             AS CurrentInventoryId,   -- InventoryId of the keeper record
            m.WarehouseLocationId  AS DuplicateLocation,    -- where the stale copy sits
            m.InventoryId          AS DuplicateInventoryId, -- InventoryId of the stale copy to remove
            m.CreatedDate,
            m.CreatedBy,
            m.ModifiedDate,
            m.ModifiedBy
        FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
        ON wal.LocationId = m.WarehouseLocationId
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON  wa.WarehouseId = wal.WarehouseId
        AND wa.AreaId      = wal.AreaId
    WHERE
        -- Exclude the keeper
        m.maxinvid <> m.InventoryId
        AND m.WarehouseLocationId NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')

        AND
    	(
    		-- Normal noise control
    		wa.IsAvailable = 1

    		OR
    		(
    			-- Override: BOTH InventoryIds have QA history
    			EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q1
    				WHERE q1.InventoryId = m.InventoryId
    			)
    			AND EXISTS (
    				SELECT 1
    				FROM InventoryCasesQaStatuses q2
    				WHERE q2.InventoryId = m.maxinvid
    			)
    		)
    	)

        ORDER BY m.ProductionDate
"""


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        # ── Store result as named DataFrame for child queries ──────────────
        try:
            import pandas as _pd
            result.dataframe = {"MaxInvIDResults": _pd.DataFrame(
                [list(r) for r in rows], columns=cols
            )}
        except Exception:
            pass

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
