"""
queries/query_missing_delivery_allocations.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db

TITLE       = "Missing Delivery Allocations"
DESCRIPTION = (
    "Checks for inventory IDs present in vwInventoryDetails "
    "(exitdeliverynumber) that have no matching record in "
    "deliveryallocations. inventoryid is the shared key."
)

# vwInventoryDetails is a view of all inventory cases with their exit delivery info.
# deliveryallocations links each inventory case to a specific delivery line.
# A case present in the view but missing from deliveryallocations means the load
# counts are inconsistent — the system sees the case as on the load but has no
# allocation record to close against, which blocks the load from closing.
# Check Delivery Allocations
SQL_BLOCK_1 = """
    SELECT   v.inventoryid
    FROM     vwInventoryDetails AS v
    WHERE    v.exitdeliverynumber = @delivery_number
      AND    NOT EXISTS (
                 SELECT 1
                 FROM   deliveryallocations AS da
                 WHERE  da.inventoryid = v.inventoryid
             )
    ORDER BY v.inventoryid
"""
_SQL_BLOCK_1_EXEC = """
    SELECT   v.inventoryid
    FROM     vwInventoryDetails AS v
    WHERE    v.exitdeliverynumber = ?
      AND    NOT EXISTS (
                 SELECT 1
                 FROM   deliveryallocations AS da
                 WHERE  da.inventoryid = v.inventoryid
             )
    ORDER BY v.inventoryid
"""


def run(delivery_number: str = "") -> QueryResult:
    result = QueryResult()
    result.add_message("info", f"[{TITLE}] Checking delivery: {delivery_number}")

    try:
        cursor = db.conn.cursor()
        cursor.execute(_SQL_BLOCK_1_EXEC, delivery_number)

        # Flatten to a plain list of ID strings — simpler to display and join for messages
        rows = [str(row[0]) for row in cursor.fetchall()]
    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    # result.data is set regardless of outcome so the result card body always has content
    result.data = rows

    if rows:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} inventory ID(s) are missing deliveryallocations records."
        result.add_message("error",   f"  ✘ {result.headline}")
        result.add_message("warning", f"    → IDs: {', '.join(rows)}")
        result.add_message("info",    "    Resolution: Recreate the missing deliveryallocations rows.")
    else:
        result.status   = "ok"
        result.headline = "No missing delivery allocations found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")

    return result
