"""
queries/query_failed_transactions.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db

TITLE       = "Failed Transactions"
DESCRIPTION = (
    "Checks for all failed transactions in the masterstaging table for the following poster types: "
    "InventoryAdjustment, OrderAcknowledgement, InventoryStatus, TrailerStatus, "
    "OrderDetailChange, ShipLoad, PorkHotCarcass."
)

# TransferStatus = -3 means the transaction failed permanently (not just pending/in-progress).
# FailReason <> '' confirms a failure message is present — avoids false positives from
# records that may have -3 status but no recorded reason.
# Detect Failed Transactions
SQL_BLOCK_1 = """
    select count(StagingId) as Count, PosterType
    from MasterStaging
    where TransferStatus = -3
        and postertype in ('InventoryAdjustment',
            'OrderAcknowledgement',
            'InventoryStatus',
            'TrailerStatus',
            'OrderDetailChange',
            'ShipLoad',
            'PorkHotCarcass')
        and FailReason <> ''
    group by PosterType
"""
_SQL_BLOCK_1_EXEC = SQL_BLOCK_1

def run() -> QueryResult:
    result = QueryResult()
    result.add_message("info", f"[{TITLE}] Checking for failed transactions...")

    try:
        cursor = db.conn.cursor()
        cursor.execute(SQL_BLOCK_1)
        rows = cursor.fetchall()
    except Exception as exc:
        result.success = False
        result.status = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result

    if not rows:
        # No rows means no failed transactions — all clear
        result.status = "ok"
        result.headline = "No failed transactions found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        # Each row is a (Count, PosterType) grouping — one entry per failing poster type.
        # The result card body lists each type and how many records are stuck.
        result.status = "issues_found"
        result.headline = f"{len(rows)} failed transaction(s) found."
        result.data = [
            f"PosterType: {row[1]}  |  Count: {row[0]}"
            for row in rows
        ]
        result.add_message("error", f"  ✘ {result.headline}")
        result.add_message("warning", f"    → Investigate the failed transactions for remediation.")

    return result
